### ISSUE TITLE
add option to disable all rules

### ISSUE THREAD

**Issue by milahu** [htacg/tidy-html5#1055]
let me disable all rules
then let me enable only the rules i want

example: tidy.conf

```yaml
# indent only, nothing else
disable-all: yes
indent: yes
```
