### ISSUE TITLE
convert attributes to double quotes

### ISSUE THREAD

**Issue by milahu** [htacg/tidy-html5#1056]
input

```html
<div id=noquotes title='single "quotes" here' class="double quotes" />
```

output

```html
<div id="noquotes" title="single &quot;quotes&quot; here" class="double quotes" />
```

the input is valid html, but some broken parsers expect attribute values in double quotes

related

https://stackoverflow.com/questions/919552/php-how-to-convert-single-quote-to-double-quote-in-all-html-tags
one answer mentions `tidy` but i did not find such an option
the `bare` option does not affect attributes

i tried this `tidy.conf`

```yaml
quiet: yes
show-warnings: no
doctype: omit
output-html: no
show-body-only: yes
bare: yes
literal-attributes: yes
strict-tags-attributes: yes
```
